### ISSUE TITLE
Site menu is broken

### ISSUE THREAD

**Issue by gasgithub** [ibm-cloud-architecture/refarch-kc#100]
Steps to reproduce:
1. Go to link https://ibm-cloud-architecture.github.io/refarch-kc/
2. Click Business problem.. > Introduction  -- generates transfer to page - https://ibm-cloud-architecture.github.io/refarch-kc/introduction - page displayed correctly
2. Click Business problem.. > Introduction  again -- generates 404 with the link https://ibm-cloud-architecture.github.io/refarch-kc/introduction/introduction   - observe additional /introduction
3. No other menu items are working then producing invalid links e.g.: 
https://ibm-cloud-architecture.github.io/refarch-kc/introduction/introduction/deployments/backing-services

Links should be fixed to be not relative to current context, but to site root.

**Comment by jbcodeforce** [comment]
Hi, thank you for this. We have ported the content to Gatsby and there are differences in the way links work. I think I fixed those yesterday
