### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lwhinson** [ibm-cloud-architecture/refarch-kc#137]
The following links, which we point to from the IBM Garage for Cloud and IBM Architecture Center websites, are opening 404s:

- https://ibm-cloud-architecture.github.io/refarch-eda/scenarios/connect-s3/
- https://ibm-cloud-architecture.github.io/refarch-kc-order-ms
- https://ibm-cloud-architecture.github.io/refarch-kc-order-ms/#data-and-event-model

If there are replacement links for those pages, please let me know. Thanks!

**Comment by osowski** [comment]
In order, the following updates can be made:

- https://ibm-cloud-architecture.github.io/refarch-eda/use-cases/connect-s3/
- https://ibm-cloud-architecture.github.io/refarch-kc/microservices/order-command/ & https://ibm-cloud-architecture.github.io/refarch-kc/microservices/order-query/
- https://ibm-cloud-architecture.github.io/refarch-kc/implementation/consume-transform-produce/

**Comment by lwhinson** [comment]
Thank you!
