### ISSUE TITLE
OpenLabs quick start using Lab6 instead

### ISSUE THREAD

**Issue by csantanapr** [ibm-cloud-architecture/refarch-kc#150]
If you switch the lab to tell the user to Lab 6 "Bring Your Own Application" that's a better experience than using Lab 1
https://ibm-cloud-architecture.github.io/refarch-kc/business-scenario/quickstart-tutorial/

![image](https://user-images.githubusercontent.com/1094878/107644098-fa6dae00-6c44-11eb-868c-4693b0911e93.png)

Using Lab 6 you can quickly find the OC console and the OC CLI login.
Also, the user would be confused with the other excersises in the left panel

This is what we recommend to users in Toolkit Workshop to use Lab 6
https://cloudnativetoolkit.dev/workshop/setup#1.-create-openshift-cluster

**Comment by osowski** [comment]
Completed and publishing via the commit above.
