### ISSUE TITLE
[quick start] Better guidance to indicate that there are 2 environment setup

### ISSUE THREAD

**Issue by csantanapr** [ibm-cloud-architecture/refarch-kc#151]
While doing the quickstart lab https://ibm-cloud-architecture.github.io/refarch-kc/business-scenario/quickstart-tutorial/

Step 1 start with getting cluster on lean.openshift website, there is no obvious indication that there is another option to get a cluster on IBM Cloud using OpenLabs. 

Maybe you make the 2 sections into carbon tab `<Tabs>`, or wrapped in a HTML section

The carbon tab would look like this
![image](https://user-images.githubusercontent.com/1094878/107644801-e9716c80-6c45-11eb-8380-8e0b02abc2f9.png)

ANd perhaps favor the IBM Cloud since can be use with Free account and extended up to 8 hours, with learn.openshift I think the environment is lost after 60 minutes.

**Comment by csantanapr** [comment]
Also favor IBM Cloud OpenShift cluster it has more resources 2 Nodes, more CPU and Mem.

The katacoda on learn.openshift sandbox is a single 16GB VM running CRC not very stable and takes very long to.

I tried today and got errors just hangs
![image](https://user-images.githubusercontent.com/1094878/107645762-1d00c680-6c47-11eb-8932-8088a46b05f9.png)

**Comment by osowski** [comment]
That timing is expected. If you open another tab and do an `oc get pods`, you'll see it's pulling all the images simultaneously, so it does take a few minutes - but nothing longer than 5 minutes. 

IME I've never hit any stability issues on the katacoda environments, especially as the quickstart was meant to be as lean as possible. If OpenLabs is going to stick around for a while, we can definitely point folks to that as the primary option.

**Comment by csantanapr** [comment]
What about the error about timeout waiting for condition?

You can address with adding an infinite using -1 

How long does usually takes? I will try again

**Comment by osowski** [comment]
I've updated the layout to move the quickstart to the top level in the navigation menu available via https://ibm-cloud-architecture.github.io/refarch-kc/quickstart-tutorial/deploy-on-ibm-openlabs/

I will update the wait time on both of the `oc wait` commands tomorrow.

**Comment by osowski** [comment]
Should be good to go with the referenced update.

**Comment by csantanapr** [comment]
Sweet 😄
