### ISSUE TITLE
Quickstart tutorial is not working

### ISSUE THREAD

**Issue by maloewer** [ibm-cloud-architecture/refarch-kc#159]
Hi Team,

I was trying todo the quickstart tutorial: 
https://ibm-cloud-architecture.github.io/refarch-kc/quickstart-tutorial/deploy-on-openshift-playgrounds/

But the script in here [kcontainer-quickstart-ocp.sh](https://github.com/ibm-cloud-architecture/refarch-kc/blob/master/scripts/quickstart/kcontainer-quickstart-ocp.sh) is cloning
https://github.com/ibm-cloud-architecture/refarch-kc-gitops .

Then it does a 

86  cd refarch-kc-gitops/environments 

and afterwards it tries to do 

135 oc apply -k dev/infrastructure/

But there is not a dev directory in environments. 
So that is broken.

Can you fix this or is there an updated guide ?

**Comment by jbcodeforce** [comment]
Hi
Thank you to report this issue. There was a folder removed from later commit. I restore it and changes cluster declaration to use last strimzi custom resource. I did a run and it deploys everything and UI is accessed. I also removed reference at the top of the tutorial. It seems fine now,
