### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by silaman** [ibm-cloud-architecture/refarch-kc#98]
The following link in https://ibm-cloud-architecture.github.io/refarch-kc/dlq/dlq/ is broken:
https://ibm-cloud-architecture.github.io/refarch-kc/dlq/containerAnomaly/containerAnomaly.md

**Comment by jesusmah** [comment]
Thanks for the finding @silaman. Also, for your awareness, this repository's documentation is undergoing an important refactoring so things are a bit temporal for now. Thanks
